moc ..\include\treewindow.h -o moc_treewindow.cpp
moc ..\include\treemodel.h -o moc_treemodel.cpp
moc ..\include\colorlisteditor.h -o moc_colorlisteditor.cpp
moc ..\include\objecteditdialog.h -o moc_objecteditdialog.cpp
moc ..\include\layereditdialog.h -o moc_layereditdialog.cpp
moc ..\include\cameraeditdialog.h -o moc_cameraeditdialog.cpp
moc ..\include\quadeditdialog.h -o moc_quadeditdialog.cpp
moc ..\include\effectslistmodel.h -o moc_effectslistmodel.cpp
moc ..\include\effectslistwindow.h -o moc_effectslistwindow.cpp
moc ..\include\effecteditdialog.h -o moc_effecteditdialog.cpp
moc ..\include\effectpages.h -o moc_effectpages.cpp
