#ifndef CONCATENACIONANIMACIONES_H_INCLUDED
#define CONCATENACIONANIMACIONES_H_INCLUDED

enum ConcatenacionAnimaciones
{
    INMEDIATO,
    ESPERAFIN
};

#endif // CONCATENACIONANIMACIONES_H_INCLUDED
